<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<META name="GENERATOR" content="IBM WebSphere Page Designer V4.0 for Windows">
<META http-equiv="Content-Style-Type" content="text/css">
<title>Corporate User</title>
<link href="<%=request.getContextPath()%>/pages/style.css" rel="stylesheet">


<jsp:useBean id="cusdata" class="datapro.eibs.beans.ESS200001Message" scope="session" />
<jsp:useBean id="error" class="datapro.eibs.beans.ELEERRMessage"  scope="session" />
<jsp:useBean id="userPO" class="datapro.eibs.beans.UserPos" scope="session" />

<script language="Javascript1.1" src="<%=request.getContextPath()%>/pages/e/javascripts/eIBS.jsp"> </SCRIPT>
<script language="Javascript1.1" src="<%=request.getContextPath()%>/pages/e/javascripts/optMenu.jsp"> </SCRIPT>
<script language="Javascript1.1">

  function SelCuentaCli(CampoDest,Campo1,Campo2,Campo3,Cliente){
     if(Cliente =="" || Cliente=="0"){
        alert("No. de Cliente debe ser Seleccionado");
        return;
     }
     GetAccByClient(CampoDest,'','','',document.forms[0].E01EUSCUN.value)
  }
  
  function GeneratePassword(){
     if(confirm("Are you sure wish generate user password ?")){
        page = "<%=request.getContextPath()%>/pages/e/ESS2000_personal_password_generated.jsp?E01EUSUSR="+document.forms[0].E01EUSUSR.value;
        CenterWindow(page,600,450,1);
     }
  }
</script>
</head>

<body bgcolor="#FFFFFF">

<%
 if ( !error.getERRNUM().equals("0")  ) {
     error.setERRNUM("0") ;
     out.println("<SCRIPT Language=\"Javascript\">");
     out.println("       showErrors()");
     out.println("</SCRIPT>");
 }
 %>


<h3 align="center">Internet Banking Corporate User<img src="<%=request.getContextPath()%>/images/e_ibs.gif" align="left" name="EIBS_GIF" ALT="cliente_corporate_new_data, ESS2000" ></h3>
<hr size="4">
<form method="post" action="<%=request.getContextPath()%>/servlet/com.datapro.eibs.internet.JSESS2000" onsubmit="return FieldNotBlank(this)">
  <INPUT TYPE=HIDDEN NAME="SCREEN" VALUE="101">
  <INPUT TYPE=HIDDEN NAME="E01EUSCTY" VALUE="1">
  <INPUT TYPE=HIDDEN NAME="E01EUSOPR" VALUE="0">  
  <INPUT TYPE=HIDDEN NAME="E01EUSCFM" VALUE="1">
  <INPUT TYPE=HIDDEN NAME="E01EUSSTS" VALUE="<%= cusdata.getE01EUSSTS() %>">
  <INPUT TYPE=HIDDEN NAME="H01FLGWK2" VALUE="<%= cusdata.getH01FLGWK2() %>">  
  
    <p align="right"><font color="RED"><B> <%= cusdata.getH01FLGWK2().equals("Y")?"NEW USER":"USER MAINTENANCE"   %></B></font> </p>  
  <table class="tableinfo">
      <tr >
        <td nowrap>

        <table cellspacing="0" cellpadding="2" width="100%" border="0" align="left">
          <tr id="trdark">
            <td nowrap width="40%" ><div align="right">Entity ID :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="text" ID="MANDATORY" name="E01EUSUSR" size="35" maxlength="10" READONLY value="<%= cusdata.getE01EUSUSR().trim()%>">
                                    <img src="<%=request.getContextPath()%>/images/Check.gif" alt="mandatory field" align="absbottom" border="0"  ></div></td>
          </tr>
          <tr id="teclear">
            <td nowrap width="40%" ><div align="right">Administrator User ID :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="text" <% if(userPO.getPurpose().equals("MAINT")){ %> READONLY <% } %> ID="MANDATORY" name="E01EUSENT" size="35" maxlength="10" value="<%= cusdata.getE01EUSENT().trim()%>">
                                    <img src="<%=request.getContextPath()%>/images/Check.gif" alt="mandatory field" align="absbottom" border="0"  ></div></td>
          </tr>
<%
if(cusdata.getH01FLGWK2().equals("Y")){
%>
          <tr id="trdark">
            <td nowrap width="40%" ><div align="right">Administrator User Password :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="password" ID="MANDATORY" name="E01EUSACP" size="35" maxlength="10" value="<%= cusdata.getE01EUSACP().trim()%>" READONLY>Autogenerated
                                    <img src="<%=request.getContextPath()%>/images/Check.gif" alt="mandatory field" align="absbottom" border="0"  >
                                    <INPUT TYPE=HIDDEN NAME="NEWUSER" VALUE="Y">
                                    </div></td>
          </tr>
<%
}
else{
%>
          <tr id="trdark">
            <td nowrap width="40%" ><div align="right">Administrator User Password :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="password" name="E01EUSACP" size="35" maxlength="10" value="<%= cusdata.getE01EUSACP().trim()%>" READONLY>
            <a href="JavaScript:GeneratePassword()" ><img src="<%=request.getContextPath()%>/images/keygen.gif" ALT="Regenerar Password" align="absbottom" border="0"  ></a> 
                                                <INPUT TYPE=HIDDEN NAME="NEWUSER" VALUE="N">
            </div></td>
          </tr>
<%
}
%>
          <!-- tr id="teclear">
            <td nowrap width="40%" ><div align="right">Administrator User Status :</div></td>
            <td nowrap width="60%" ><div align="left"><SELECT NAME="E01EUSSTS">
             <OPTION VALUE="1" <%if (cusdata.getE01EUSSTS().equals("1")) {out.print("selected"); }%>>ACTIVE</OPTION>
             <OPTION VALUE="2" <%if (cusdata.getE01EUSSTS().equals("2")) {out.print("selected"); }%>>INACTIVE</OPTION>
             <OPTION VALUE="3" <%if (cusdata.getE01EUSSTS().equals("3")) {out.print("selected"); }%>>SUSPENDED</OPTION>
             <OPTION VALUE="4" <%if (cusdata.getE01EUSSTS().equals("4")) {out.print("selected"); }%>>PENDING ACTIVATION</OPTION>
             </SELECT></div></td>
          </tr -->
          <tr id="trdark">
            <td nowrap width="40%" ><div align="right">Customer Number :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="text" ID="MANDATORY" name="E01EUSCUN" size="35" maxlength="9" value="<%= cusdata.getE01EUSCUN().trim()%>">
                                    <a href="javascript:GetCustomerDescId('E01EUSCUN','E01EUSCON','')"><img src="<%=request.getContextPath()%>/images/1b.gif" alt="Help" border="0" ></a>
                                    <img src="<%=request.getContextPath()%>/images/Check.gif" alt="mandatory field" align="absbottom" border="0"  ></div></td>
          </tr>
          <tr id="teclear">
            <td nowrap width="40%" ><div align="right">Primary Account Number :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="text" ID="MANDATORY" name="E01EUSACC" size="35" maxlength="9" value="<%= cusdata.getE01EUSACC().trim()%>" onkeypress="enterInteger()">
                                    <a href="javascript:GetAccount('E01EUSACC','','','')"><img src="<%=request.getContextPath()%>/images/1b.gif" alt="Help" border="0" ></a>
                                    <img src="<%=request.getContextPath()%>/images/Check.gif" alt="mandatory field" align="absbottom" border="0"  ></div></td>
          </tr>
          <tr id="trdark">
            <td nowrap width="40%" ><div align="right">Maximum Acumulated Type :</div></td>
            <td nowrap width="60%" ><div align="left"> <SELECT NAME="E01EUSMXT">
             <OPTION VALUE="1" <%if (cusdata.getE01EUSMXT().equals("1")) {out.print("selected"); }%>>DAILY MAXIMUN AMOUNT PERMITTED</OPTION>
             <OPTION VALUE="2" <%if (cusdata.getE01EUSMXT().equals("2")) {out.print("selected"); }%>>WEEKLY MAXMIMUN AMOUNT PERMITTED</OPTION>
             </SELECT></div></td>
          </tr>
          <tr id="teclear">
            <td nowrap width="40%" colspan="2" align="center">
				   <TABLE width="70%">
				      <TR>
				         <TD colspan="4" align="center" ><b>TRANSACTIONS PERMISSION</b></TD>
				      </TR>
					  <tr align="center" id="trdark">
					     <TD>Transaction</TD>
					     <TD>Transaction Limit</TD>
					     <TD>Acumulated Limit</TD>
					  </tr>
					  <tr align="center">
					     <TD align="right">Internal Transfer :</TD>
					     <TD><input type="text" name="E01EUSMAX" size="25" maxlength="11" value="<%= cusdata.getE01EUSMAX().trim()%>"></TD>
					     <TD><input type="text" name="E01EUSAMX" size="25" maxlength="11" value="<%= cusdata.getE01EUSAMX().trim()%>"></TD>
					  </tr>					  
					  <tr align="center">
					     <TD align="right">Third Party Transfer :</TD>
					     <TD><input type="text" name="E01EUSTTL" size="25" maxlength="11" value="<%= cusdata.getE01EUSTTL().trim()%>"></TD>
					     <TD><input type="text" name="E01EUSTAL" size="25" maxlength="11" value="<%= cusdata.getE01EUSTAL().trim()%>"></TD>
					  </tr>					  
					  <tr align="center">
					     <TD align="right">External Transfer :</TD>
					     <TD><input type="text" name="E01EUSETL" size="25" maxlength="11" value="<%= cusdata.getE01EUSETL().trim()%>"></TD>
					     <TD><input type="text" name="E01EUSEAL" size="25" maxlength="11" value="<%= cusdata.getE01EUSEAL().trim()%>"></TD>
					  </tr>					  
					  <tr align="center">
					     <TD align="right">Bill Payable Permitted :</TD>
					     <TD></TD>
					     <TD></TD>
					  </tr>					  
					  <tr align="center">
					     <TD align="right">Letter of Credits Permitted :</TD>
					     <TD></TD>
					     <TD></TD>
					  </tr>					  
					  <tr align="center">
					     <TD align="right">Loans Payable Permitted : </TD>
					     <TD></TD>
					     <TD></TD>
					  </tr>					  
					  <tr align="center">
					     <TD align="right">Credit Card Payable Permitted : </TD>
					     <TD></TD>
					     <TD></TD>
					  </tr>					  
				   </TABLE>            
            </td>
          </tr>
                    
          <tr id="trdark">
            <td nowrap width="40%" ><div align="right">Person Responsible :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="text" name="E01EUSCON" size="35" maxlength="30" value="<%= cusdata.getE01EUSCON().trim()%>"></div></td>
          </tr>
          <tr id="teclear">
            <td nowrap width="40%" ><div align="right">E-Mail Address :</div></td>
            <td nowrap width="60%" ><div align="left"> <input type="text" ID="MANDATORY" name="E01EUSIAD" size="35" maxlength="45" value="<%= cusdata.getE01EUSIAD().trim()%>">
                                    <img src="<%=request.getContextPath()%>/images/Check.gif" alt="mandatory field" align="absbottom" border="0"  ></div></td>
          </tr>
        </table>
        </td>
      </tr>
    </table>

  <p align="center"> <input id="EIBSBTN" type=submit name="Submit" value="Submit"> </p>
</form>
</body>
</html>
