/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ui;

import core.file.Cleaner;
import core.file.FileMatcher;
import core.file.FileProcessor;
import core.file.LogCentral;
import core.file.Profile;
import java.awt.Component;
import java.nio.file.Path;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author cbaez
 */
public class ExecutionPanel extends javax.swing.JPanel {

    Profile profile;
    FileMatcher fileMatcher;
    FileProcessor fileProcessor;

    /**
     * Creates new form ExecutionPanel
     */
    public ExecutionPanel(Profile profile) {
        this.profile = profile;

        initComponents();
    }

    public void loadMatchedFiles() {

        DefaultListModel<Path> filesDataModel = new DefaultListModel<>();
        profile.getFileCentral().getMatchedFiles().forEach(p -> filesDataModel.addElement(p));
        jLabel1.setText(profile.getFileCentral().getMatchedFiles().size() + " files matched");
        matchedFilesList.setModel(filesDataModel);

    }

    public void previewProcess(Path path){
        DefaultListModel<Cleaner> listModel = new DefaultListModel<>();
        List<Cleaner> assignedCleaners = fileProcessor.getAssignedCleaners(path);
        assignedCleaners.forEach(c -> {
            listModel.addElement(c);
        
        });
        processedFilesList.setModel(listModel);
    }
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        matchedFilesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        matchedFilesList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        processedFilesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        processedFilesList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        previewFilePanel = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        matchedFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Matched"));
        matchedFilesPanel.setLayout(new java.awt.BorderLayout());

        matchedFilesList.setCellRenderer(new DefaultListCellRenderer(){

            public Component getListCellRendererComponent(JList<? extends Path> list, Path p, int index,
                boolean isSelected, boolean cellHasFocus) {
                this.setText(p.getFileName().toString());
                return this;
            }
        }
    );
    matchedFilesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            matchedFilesListValueChanged(evt);
        }
    });
    jScrollPane2.setViewportView(matchedFilesList);

    matchedFilesPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    jPanel3.setLayout(new java.awt.BorderLayout());

    jLabel1.setText("0 matched");
    jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

    matchedFilesPanel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

    jSplitPane1.setTopComponent(matchedFilesPanel);

    processedFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Processed"));
    processedFilesPanel.setLayout(new java.awt.BorderLayout());

    jScrollPane3.setViewportView(processedFilesList);

    processedFilesPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

    jPanel4.setLayout(new java.awt.BorderLayout());

    jLabel2.setText("0 processed");
    jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

    processedFilesPanel.add(jPanel4, java.awt.BorderLayout.PAGE_END);

    jSplitPane2.setLeftComponent(processedFilesPanel);

    previewFilePanel.setLayout(new java.awt.BorderLayout());
    previewFilePanel.add(jSplitPane3, java.awt.BorderLayout.CENTER);

    jSplitPane2.setRightComponent(previewFilePanel);

    jSplitPane1.setRightComponent(jSplitPane2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void matchedFilesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_matchedFilesListValueChanged
        Path path = (Path) matchedFilesList.getSelectedValue();
        previewProcess(path);
    }//GEN-LAST:event_matchedFilesListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JList matchedFilesList;
    private javax.swing.JPanel matchedFilesPanel;
    private javax.swing.JPanel previewFilePanel;
    private javax.swing.JList processedFilesList;
    private javax.swing.JPanel processedFilesPanel;
    // End of variables declaration//GEN-END:variables
}
